### ISSUE TITLE
Clicking on the notification can not Enter to  The task

### ISSUE THREAD

**Issue by darshanamhaske** [madrecha/jamku#825] opened 2021-12-03 11:33 UTC
### Feature Request

**Suggestion** 

**Clicking on the notification can not Enter to  The task**

`By : Shailesh Jaiswal`

When we received any notification from jamku,
user tries to click on that notification,
The user cannot access the Task Or Tasks Dashboard.

**Comment by adarshmadrecha** [comment] 2021-12-07 05:24
Duplicate of #797

**Closed by adarshmadrecha** 2021-12-07 05:24 UTC
Labels: bug
